# ----
# Site

title: Aperture Template
url: "http://footballcloud.net/"
baseurl:
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Apasionado, Estimulante, Sensato, Experientado, Metódico y Ejemplar.
author:
  name: EnriqueAlvarez
  email: 
  twitter: perisperis
social:
  name: Aperture Template
  links:
    - https://github.com/CloudCannon/aperture-jekyll-template

# -----
# Build

timezone: Etc/UTC

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      text_width: true
      image: /uploads/1.jpg
  -
    scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENCE

# -----------
# CloudCannon

_options:
  image:
    width: 2048
    height: 1365
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: true
theme: jekyll-theme-cayman